import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "../component/header"
import Footer from "../component/footer"
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className="flex h-screen flex-col items-center gap-[50px] 2xl:gap-[40px] w-[90%]  m-auto">
       <Header/>
       
        <main className="w-full mt-[100px] md:mt-[160px] 2xl:mt-[180px]">
        {children}
        </main>
        <Footer/>
       </div>
      </body>
    </html>
  );
}
